### ISSUE TITLE
PR #1070 - Comments and concerns

### ISSUE THREAD

**Issue by W3stside** [gnosis/cowswap#1085]
Merges in #1070
--
HI @W3stside , great job! 
Some minor issues: 
1. I'm not sure whether it is an issue or not, but 'Slippage tolerance' appears on the Swap form when I change it manyally in the settings. When the setting is 'Auto', 'Slippage tolerance' is not displayed on the form
https://drive.google.com/file/d/19wjFS41uX3qWb6h4cf870R_542KOxlkC/view

2. Price USD estimation is different on the Swap form and in the Confirmation modal (difference is about 0.01$). I assume, it should be the same
![image](https://user-images.githubusercontent.com/70885163/127292442-b7a0b1ff-fab7-4b48-ac49-3a1f90f72df9.png)
![2](https://user-images.githubusercontent.com/70885163/127292460-f2175f48-b224-458c-af1e-9934723c36c8.jpg)

3. Prices are jumping when invert them: 
 - when USD amount is loaded: https://drive.google.com/file/d/1ecadUoMNmCDuz2lbQk_SquVfM4CVSnPN/view
 - when invert them on a Mobile screen: https://drive.google.com/file/d/1QogvmwHlS3pLzxkwMb17HsJFsPQj-LgW/view
 - when invert prices on the Confirmation modal on a Mobile screen: https://drive.google.com/file/d/1H4yIb5qfnAkCWkhd6yRPRO5h8Sj0yEbR/view

4. Not a priority, but Price/Fee/Slippage values sometimes look like have a different alignment.. IMHO
![image](https://user-images.githubusercontent.com/70885163/127293720-20ca3efd-f7c6-4360-9580-7796ab7e0b02.png)

_Originally posted by @elena-zh in https://github.com/gnosis/cowswap/issues/1070#issuecomment-888135053_

## Tasks
- [ ] address jumping amounts (re-input placeholder amounts)
- [ ] fix Price // Slippage // Fee styles
- [x] Remove fee amount USD estimation

**Comment by W3stside** [comment]
closing as separate issues already made
