### ISSUE TITLE
[Epic] Support of Smart Contract Wallets

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#1305]
# Description
Implement basic functionality to allow Smart Contract Wallets to trade:

*  **Initial analysis on Pre-sign**: https://docs.google.com/document/d/1WapgdKttPwftOV-u2nItddkMU_ifUuUlVKSy5X1xCgY/edit#
* **Analysis of Gnosis safe workflow and state of the apps**: https://docs.google.com/document/d/1qMvidoxpl4e7SQ5pH9nSuhGEzh3AdjYEYXzDnjQBiqg/edit
* **Notes on the consolidation of several PRs**: Contain some comments and issues from intermediate PRs that we should double check before closing this issue: https://docs.google.com/document/d/1_I0yPgocBqbKGnFLC1L3nvlS3nMXZcNLOPhvR8YAxi4/edit 

## Edit 4/11/2021
Now, we are just polishing last thing s!

IMPORTANT
- [X] #1720
- [X] #1783
- [x]  #1797 
- [x]  #1791 

SMALL BUGS
- [ ] #1622
- [ ] Cancelation/override tx logics doesnt work for Gnosis Safe

GOOD TO HAVE:
- [x] #1612
- [ ] #1624
- [ ] Improve useWalletInfo. It's inneficient

NOT IN THIS LIST
- All that has to be with the explorer will be addressed in other issues

## Edit 13/10/2021
Lot's of work has been done, so I want just to update what would be left for a release

### CowSwap important:
* [X] Estimate gas for Gnosis Safe doesn't work: breaks the app. Reproduce by unwrapping ETH https://github.com/gnosis/cowswap/issues/1469 https://github.com/gnosis/cowswap/pull/1562
- [X] #1566 
- [X] #1595
- [x] #1623
- [x] #1596
- [x] #1597
- [x] #1598
- [x] #1599

### Other

- [ ] Change the name for OPEN tx? and show the pending effect?
- [x] - [ ] Handle cancelation in Gnosis Safe and edge cases
- [x] Handle rejection or failed Safe transactions. See 7. and 9. in https://github.com/gnosis/cowswap/pull/1370#issuecomment-915166211
- [x] Reject tx doesn't work using WalletConnect
- [x] 1. Link on confirmation toast notification navigates to a not existing TxHash page (example - https://rinkeby.etherscan.io/tx/0x91dd1599ecdd4bc70b10def608e78237a5e5b81c8bd62ce2df3c3a71a4a386f5 )
- [x] 2. When reject signing transaction in the Safe by all owners, the transaction hangs in 'Open' status
- [x] 3. When a transaction fails, the same: the transaction hangs in 'Open' status
- [x] 4. I was not able to run 'Wrap' transaction in XDAI. I always got failed transaction in MM when signing it =(
- [x] Fix issues with Gnosis Safe UX described in the document. Will create probably several PRs trying different things. Some of the issues are also described in 3. and 4. in https://github.com/gnosis/cowswap/pull/1370#issuecomment-915166211 https://docs.google.com/document/d/1_I0yPgocBqbKGnFLC1L3nvlS3nMXZcNLOPhvR8YAxi4/edit 

### 🎸Improvements
Good to haves (not required for version, keeping them for now)
* [No now] ~[Michel] Manage better the expectations about cost~: #1342, #1143
* [No] ~Toast notification when the pre-sign is done~
* [No now] Improve how we show the costs: 
* [X] It's possible that the Swap notification is shown before detecting the Gnosis Safe swap has all the signatures. See comment https://github.com/gnosis/cowswap/pull/1652#pullrequestreview-782416652

# Before 13/10/2021

 
## ⚡️ Basic
* [x] #1313
* [x] #1314, #1329
* [x] #1366
* [x] #1367
* [x] #1369
* [x] #1370 
* [x] #1408
* [X] [Michel] Confirmation modal when you Approve/Wrap/Unwrap that informs that you should sign the tx in the wallet: https://github.com/gnosis/cowswap/pull/1483 

## 🔨 Improvements
* [X] Load/represent Presign status
* [x] #1334 
* [x] Show a popup while the transaction is being signed. Right now, normal transactions don't do anything when you click on the button. (See 2. in https://github.com/gnosis/cowswap/pull/1370#issuecomment-915166211)

## ⚡️ Gnosis Safe Transactions: awareness and basic flow
* [x] Analyze Gnosis Safe Apps and behavious: https://docs.google.com/document/d/1qMvidoxpl4e7SQ5pH9nSuhGEzh3AdjYEYXzDnjQBiqg/edit# 
* [X] PoC SDK: https://github.com/gnosis/cowswap/pull/1414
* [X] PoC Safe transaction API (using client)
* [X] Enhance Transaction support (redux/actions), so we can freely attach info to transactions and control the updaters/hookshttps://github.com/gnosis/cowswap/pull/1429
* [x] https://github.com/gnosis/cowswap/pull/1430
* [X] https://github.com/gnosis/cowswap/pull/1467
* [x] https://github.com/gnosis/cowswap/pull/1488

## ⚡️ Gnosis Safe Orders: awareness and basic flow
* [X] Enhance order state, to have the presign gnosis safe data info
* [X] Improve the updater so it keeps track of gnosis safe presign orders
* [X] Add Gnosis Safe context in "Recent activity" so users know if there's missing signatures for the presign
* [X] Handle the confirmation of the presign orders

## 🧹 Some fixes
* [X] #1391 
* [X] #1416
* [X] Don't try to open the safe transaction hashes in Etherescan. We could add an additional link to the Safe while the transaction is not created
* [X] Get Gnosis Safe transaction, execution tx and receipt, and finalize

**Comment by alfetopito** [comment]
Wallet list sheet https://docs.google.com/spreadsheets/d/177RoN3x0gHDwKAgu-TXUYEuz-z-dPu3RybZvOumRrAA/edit#gid=0

The only other SC wallet I know of (besides Gnosis Safe and Argent) is Pillar https://www.pillar.fi/

**Comment by biocom** [comment]
Is it to be expected that regular (EOA) orders are marked as pre-sign orders? Been testing on Rinkeby and see the orders being submitted as `Pre-sign order has been sent with: `

**Comment by alfetopito** [comment]
> Is it to be expected that regular (EOA) orders are marked as pre-sign orders? Been testing on Rinkeby and see the orders being submitted as `Pre-sign order has been sent with: `

That is only on this PR for testing the flow. So yes, it's expected, for now.
