### ISSUE TITLE
Affiliate program

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#1575]
**Description**

Affiliate program for CowSwap

Composed of 2 main parts:
1. Profile page to display info regarding own trades and referrals trades
2. Affiliate flow for people following affiliate link

**Additional resources**

**Feature breakdown**
It includes:
- [x] Wire up flow https://github.com/gnosis/cowswap/pull/1405
- [x] Warn about invalid referral link #1570 
- [x] Warn stats only available on mainnet https://github.com/gnosis/cowswap/issues/1512
- [x] Different banner styles #1571 
- [x] Banner disappears on reload #1572 
- [x] Banners behaviour when changing accounts #1573 
- [x] Integrate profile page data source https://github.com/gnosis/cowswap/pull/1506
- [x] Profile page misc UI issues https://github.com/gnosis/cowswap/issues/1545
- [x] Profile page tooltips https://github.com/gnosis/cowswap/issues/1567
- [x] Affiliate status messages https://github.com/gnosis/cowswap/issues/1343
- [x] Profile: add a loader when user details are updated https://github.com/gnosis/cowswap/issues/1632
- [x] FAQ entry for number of trades https://github.com/gnosis/cowswap/issues/1705
- [x] Notify user about error fetching data https://github.com/gnosis/cowswap/issues/1698
- [x] Typo on `volume` https://github.com/gnosis/cowswap/issues/1699
- [x] Add profile page to the top of page https://github.com/gnosis/cowswap/issues/1701
- [x] Center align `connect wallet` button https://github.com/gnosis/cowswap/issues/1702
- [x] Hide msg when wallet is disconnected https://github.com/gnosis/cowswap/issues/1704
- [x] Invalid affiliate code shown after successful trade https://github.com/gnosis/cowswap/issues/1707
- [ ] Add info about currently followed affiliate link https://github.com/gnosis/cowswap/issues/1708
- [x] Remember decision when banner is dismissed #1730
- [x] Make info msg corners rounded #1738
- [x] Remove referral from local storage when query parameter is not present and the page is refreshed #1749
- [x] Remove `?referral=` from url when code is empty #1750 
- [x] Mobile profile page margins #1751 
- [x] Mobile sections width #1752 

*Note*: Lot's of PRs/issues already completed not included in this list. ONly added the ones that are pending/in progress

**Comment by elena-zh** [comment]
Affiliate program has been implemented.
