### ISSUE TITLE
Technical debt

### ISSUE THREAD

**Issue by alfetopito** [gnosis/cowswap#1887]
**Description**

Epic to track technical debt

**Performance related**
- [ ] Take a look at proper library tree shaking, big libraries, or big JSONS of unused ABIs
- [ ] Build time speedup: Bottle necks, unused things that we can ignore in typescript, or webpack
- [ ] Token list
  - [ ] Enable Coingecko
  - [ ] Optimize list loading performance
- [ ] Optimize token balance balance checks
- [ ] Check if/why price fetching is slow/makes the app slow
- [ ] Check whether SWR would be a good fit for optmizing data fetching/caching/retries: https://swr.vercel.app/docs/getting-started

**Error handling**
- [ ] console.logs! During app start up, during app execution
- [ ] Sentry: Go over unhandled errors
- [ ] Barn for explorer

**Tracking**
- [ ] Analytics for affiliate
  - [ ] Track copy button?
  - [ ] Links followed - probably already on google analytics

**Comment by anxolin** [comment]
This is important, Staly!
