### ISSUE TITLE
Improve wrap ETH workflow and context

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#1943]
Epic with tasks or ideas to improve the workflow of ETH

* [x] https://github.com/gnosis/cowswap/issues/1853
* [ ] Show ETH wrapping in a modal an re-shape the workflow? https://gnosisinc.slack.com/archives/C025G521XQD/p1637069215012300 
* [ ] What other actions could we take to make this easier? validate with users
* [ ] Bundling wrap / approve (+ ideally also 1st trade also for smart contract)
