### ISSUE TITLE
[Error Handling] address issues in PR

### ISSUE THREAD

**Issue by W3stside** [gnosis/cowswap#751]
- [x] Quote error enum: https://github.com/gnosis/cowswap/pull/745#discussion_r647556310 and https://github.com/gnosis/cowswap/issues/764 - done in #766 
- [x] Just use enum in error instead of attaching to class: https://github.com/gnosis/cowswap/pull/746#discussion_r647574720 - done in #766 
- [x] fix pathing (make absolute) - done in #766 
- [x] fix vague promise comments in useRefetch and utils - done in #766 
- [ ] (maybe for later) handle "unhandled error" for quote fetch: https://github.com/gnosis/cowswap/pull/747#discussion_r647597184

**Comment by anxolin** [comment]
Good call joining comments in one issue to not lose track and deal with a big waterfall :)
